### PR TITLE
fix: avoid re-encoding cover images when possible

### LINKED ISSUE #151: Dont re-encode cover photo
Some podcasts have a cover photo on the mp3 file, which ffmpeg detects as a video stream.
```
Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 306x306 [SAR 150:150 DAR 1:1], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
```

When embedding metadata, the ffmpeg command copies the audio stream with `-c:a copy`. But it doesn't give anything for `-c:v`. This means ffmpeg will use default codecs to re-encode the video stream.

After using `--embed-metadata` , the cover photo is re-encoded to a png:

```
  Stream #0:1: Video: png, rgb24(pc, gbr/unknown/unknown), 306x306 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, start 0.012000 (attached pic)
    Metadata:
      comment         : Cover (front)
```

Avoid re-encoding the cover photo. Lossy-to-lossy re-encoding is bad.

### PR DESCRIPTION
**Pull request by lightpohl**
- Avoid re-encoding cover images when possible
- The main problematic path was when using `--embed-metadata` with no other `ffmpeg` related flags

Fixes #151

### CODE REVIEW

**Comment by paschun** [comment]
The `-c copy` looks right. Never used `-disposition`, apparently it is used to embed a cover image? Looks fine to me.

Thank you!

File: bin/ffmpeg.js [hunk 1]
```diff
@@ -40,15 +41,23 @@ export const runFfmpeg = async ({
...
     const supportsAttachedPic = targetFormat
       ? targetFormat.attachedPic
       : Object.values(AUDIO_FORMATS).find((f) => f.ext === ext)?.attachedPic;
-    command += supportsAttachedPic ? ` -c:v copy -disposition:v:0 attached_pic` : ` -c:v copy`;
+    if (usedFullStreamCopy) {
+      if (supportsAttachedPic) {
+        command += ` -disposition:v:0 attached_pic`;
+      }
+    } else {
+      command += supportsAttachedPic ? ` -c:v copy -disposition:v:0 attached_pic` : ` -c:v copy`;
```
Comment (paschun) [inline bin/ffmpeg.js]: All these branches are a little confusing maybe could be simplified

Comment (lightpohl) [reply bin/ffmpeg.js]: Moved targeting booleans up and simplified the conditionals. 👍

**Comment by paschun** [comment]
looks great 👍
